# Site settings
title: Vishnu Sharma
description: Vishnu Sharma
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Vishnu Sharma
  title: Java Developer
  address: Sector 135 Noida, India
  email: talkto@vishnusharma.dev
  link: http://ddbullfrog.com
  weibo:
  github: vishnudixit
  linkedin: vishnu-d-sharma
  twitter: DixitVishnu
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Tubelight Communications Limited
      location: Sector 135 Noida, India
      title: Lead Technology(Java)
      started: 2016
      duration: (2016 - Present)
      description:   Finding the best tech solution among all possible to solve the existing business problems.
                     Describing the structure, characteristics, behavior, and other aspects of software to project stakeholders.
                     Defining features, phases, and solution requirements.
                     Providing specifications according to which the solution is defined, managed, and delivered.
                     Analyzing the technology environment
                     Analyzing enterprise specifics
                     Analyzing and documenting requirements
                     Setting the collaboration framework
                     Creating a solution prototype
                     Participating in technology selection
                     Controlling solution development
                     Supporting project management
                     Smart planning of complex tasks on hand with details to proceed to the next level with impact analysis. 
                     Innovating new products & solutions which are market changing for the company
                     Improvising & Optimizing existing products, solutions to invest in next generation technology
                     Identifying alliances ahead of time & excelling in cross sites collaboration
                     Provide technical support and consultation for java application and infrastructure questions. 
                     Establish, refine and integrate development and test environment tools and software as needed.
                     Analyse database schema's, data models, and data integration requirements
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Hindi
      proficiency: Proficient
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Java/JEE
      percentage: 90%
    - skill2:
      name: Spring Boot
      percentage: 80%
    - skill3:
      name: Hibernate
      percentage: 80%
    - skill4:
      name: Asterisk
      percentage: 80%
    - skill5:
      name: PHP
      percentage: 90%
    - skill6:
      name: Java Script
      percentage: 70%
    - skill7:
      name: Python
      percentage: 70%
    - skill8:
      name: Big Data
      percentage: 70% 
    - skill9:
      name: Design Patterns
      percentage: 70%
    - skill10:
      name: VXML
      percentage: 90%
    - skill11:
      name: Machine Learnig/Artificial Intelligence
      percentage: 70%
    - skill12:
      name: Deep Learning
      percentage: 70%
